-- DOSSORA — seed.sql (données de démonstration) — à exécuter UNE seule fois après schema.sql et policies.sql.
-- Généré par scripts/generate-demo.mjs. Les visuels /demo/*.svg sont des créations originales libres de droits.
-- Les tarifs de livraison et taux de change ci-dessous sont des EXEMPLES à modifier dans Admin → Livraison.

insert into public.shop_settings (key, value) values ('general', '{"shop_name":"DOSSORA","slogan":"L''élégance à votre portée","currency":"MAD","email":"dossorashop@gmail.com","whatsapp":"212603391255","announcement_fr":"Livraison internationale • Paiement à la livraison au Maroc","announcement_en":"International delivery • Cash on delivery in Morocco","announcement_ar":"توصيل دولي • الدفع عند الاستلام في المغرب"}'::jsonb) on conflict (key) do nothing;

insert into public.categories (slug, parent_id, name_fr, name_en, name_ar, description_fr, description_en, description_ar, image_url, sort_order) values
('sacs', null, 'Sacs', 'Bags', 'حقائب', 'Des sacs pensés pour sublimer chaque tenue.', 'Bags designed to elevate every outfit.', 'حقائب مصممة لتُبرز جمال كل إطلالة.', '/demo/cat-sacs.svg', 1),
('vetements', null, 'Vêtements', 'Clothing', 'ملابس', 'Coupes fluides et matières nobles.', 'Fluid cuts and refined fabrics.', 'قصّات انسيابية وأقمشة راقية.', '/demo/cat-vetements.svg', 3),
('chaussures', null, 'Chaussures', 'Shoes', 'أحذية', 'Confort et élégance, du matin au soir.', 'Comfort and elegance, morning to night.', 'راحة وأناقة من الصباح إلى المساء.', '/demo/cat-chaussures.svg', 5),
('beaute', null, 'Beauté', 'Beauty', 'الجمال', 'Des rituels de soin inspirés du savoir-faire marocain.', 'Care rituals inspired by Moroccan craftsmanship.', 'طقوس عناية مستوحاة من الحرفية المغربية.', '/demo/cat-beaute.svg', 6),
('accessoires', null, 'Accessoires', 'Accessories', 'إكسسوارات', 'Le détail qui fait toute la différence.', 'The detail that makes all the difference.', 'التفصيل الذي يصنع الفرق.', '/demo/cat-accessoires.svg', 7),
('maison', null, 'Maison', 'Home', 'المنزل', 'Des détails raffinés pour un intérieur accueillant.', 'Refined details for a welcoming home.', 'تفاصيل أنيقة لمنزل دافئ.', '/demo/cat-maison.svg', 34)
on conflict (slug) do nothing;

insert into public.categories (slug, parent_id, name_fr, name_en, name_ar, sort_order)
select v.slug, p.id, v.fr, v.en, v.ar, v.o from (values
('sacs-a-main', 'sacs', 'Sacs à main', 'Handbags', 'حقائب يد', 2),
('sacs-a-dos', 'sacs', 'Sacs à dos', 'Backpacks', 'حقائب ظهر', 8),
('sacs-bandouliere', 'sacs', 'Sacs bandoulière', 'Crossbody bags', 'حقائب كتف', 9),
('sacs-soiree', 'sacs', 'Sacs de soirée', 'Evening bags', 'حقائب سهرة', 10),
('sacs-professionnels', 'sacs', 'Sacs professionnels', 'Work bags', 'حقائب عمل', 11),
('pochettes', 'sacs', 'Pochettes', 'Clutches', 'حقائب يد صغيرة', 12),
('mini-sacs', 'sacs', 'Mini sacs', 'Mini bags', 'حقائب صغيرة', 13),
('cabas', 'sacs', 'Cabas', 'Tote bags', 'حقائب كبيرة', 14),
('robes', 'vetements', 'Robes', 'Dresses', 'فساتين', 4),
('chemisiers', 'vetements', 'Chemisiers', 'Blouses', 'بلوزات', 15),
('hauts', 'vetements', 'T-shirts', 'T-shirts', 'قمصان', 16),
('pantalons', 'vetements', 'Pantalons et jeans', 'Trousers and jeans', 'سراويل وجينز', 17),
('jupes', 'vetements', 'Jupes', 'Skirts', 'تنانير', 18),
('vestes', 'vetements', 'Vestes et pulls', 'Jackets and sweaters', 'سترات وكنزات', 19),
('ensembles', 'vetements', 'Ensembles', 'Co-ord sets', 'أطقم', 20),
('sport', 'vetements', 'Vêtements de sport', 'Activewear', 'ملابس رياضية', 21),
('baskets', 'chaussures', 'Baskets', 'Sneakers', 'أحذية رياضية', 22),
('talons', 'chaussures', 'Talons', 'Heels', 'أحذية بكعب', 23),
('sandales', 'chaussures', 'Sandales', 'Sandals', 'صنادل', 24),
('mocassins', 'chaussures', 'Mocassins', 'Loafers', 'أحذية بدون كعب', 25),
('bottines', 'chaussures', 'Bottines', 'Ankle boots', 'أحذية قصيرة', 26),
('accessoires-chaussures', 'chaussures', 'Chaussures de soirée et casual', 'Evening and casual shoes', 'أحذية سهرة وكاجوال', 27),
('savons', 'beaute', 'Savons et gels douche', 'Soaps and shower gels', 'صابون وجل استحمام', 28),
('soins-visage', 'beaute', 'Soins du visage', 'Face care', 'العناية بالوجه', 29),
('soins-corps', 'beaute', 'Soins du corps', 'Body care', 'العناية بالجسم', 30),
('parfums', 'beaute', 'Huiles et parfums', 'Oils and perfumes', 'زيوت وعطور', 31),
('bijoux', 'accessoires', 'Bijoux et montres', 'Jewelry and watches', 'مجوهرات وساعات', 32),
('mode-accessoires', 'accessoires', 'Lunettes, ceintures et foulards', 'Sunglasses, belts and scarves', 'نظارات وأحزمة وأوشحة', 33),
('decoration', 'maison', 'Décoration', 'Decor', 'ديكور', 35),
('rangement', 'maison', 'Rangement', 'Storage', 'تنظيم', 36),
('salle-de-bain', 'maison', 'Salle de bain', 'Bathroom', 'الحمام', 37)
) as v(slug, parent, fr, en, ar, o) join public.categories p on p.slug = v.parent on conflict (slug) do nothing;

insert into public.products (slug, sku, category_id, name_fr, name_en, name_ar, description_fr, description_en, description_ar, price, sale_price, status, is_featured, is_popular, is_new, is_on_sale)
select v.slug, v.sku, c.id, v.fr, v.en, v.ar, v.dfr, v.den, v.dar, v.price, v.sale, 'published', v.f, v.p, v.n, v.s from (values
('sac-riviera', 'DOS-001', 'sacs-a-main', 'Sac à main Riviera', 'Riviera handbag', 'حقيبة يد ريفييرا', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 890::numeric, null::numeric, true, true, false, false),
('sac-bandouliere-aurore', 'DOS-002', 'sacs', 'Sac bandoulière Aurore', 'Aurore crossbody bag', 'حقيبة كتف أورورا', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 640::numeric, 520::numeric, false, false, false, true),
('cabas-signature', 'DOS-003', 'sacs', 'Cabas Signature', 'Signature tote', 'حقيبة كبيرة سيغنتشر', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 1150::numeric, null::numeric, false, false, true, false),
('robe-satin-soraya', 'DOS-004', 'robes', 'Robe satin Soraya', 'Soraya satin dress', 'فستان ساتان سورايا', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 780::numeric, null::numeric, true, true, false, false),
('abaya-elegance', 'DOS-005', 'vetements', 'Abaya Élégance', 'Élégance abaya', 'عباءة أناقة', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 950::numeric, 790::numeric, false, false, false, true),
('chemise-lin-nadia', 'DOS-006', 'vetements', 'Chemise en lin Nadia', 'Nadia linen shirt', 'قميص كتان نادية', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 420::numeric, null::numeric, false, false, true, false),
('escarpins-velours', 'DOS-007', 'chaussures', 'Escarpins velours', 'Velvet pumps', 'حذاء مخملي بكعب', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 690::numeric, null::numeric, false, true, false, false),
('sandales-dorees-mira', 'DOS-008', 'chaussures', 'Sandales dorées Mira', 'Mira golden sandals', 'صندل ذهبي ميرا', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 480::numeric, 390::numeric, false, false, false, true),
('baskets-creme', 'DOS-009', 'chaussures', 'Baskets crème', 'Cream sneakers', 'حذاء رياضي كريمي', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 560::numeric, null::numeric, false, false, true, false),
('savon-rose-argan', 'DOS-010', 'savons', 'Savon rose & argan', 'Rose & argan soap', 'صابون الورد والأرغان', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 55::numeric, null::numeric, false, true, false, false),
('savon-noir-beldi', 'DOS-011', 'savons', 'Savon noir beldi', 'Beldi black soap', 'الصابون الأسود البلدي', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 45::numeric, null::numeric, false, false, false, false),
('coffret-savons-dossora', 'DOS-012', 'savons', 'Coffret de savons DOSSORA', 'DOSSORA soap gift set', 'طقم صابون دوسورا', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 210::numeric, null::numeric, true, false, true, false),
('foulard-soie-ivoire', 'DOS-013', 'accessoires', 'Foulard soie ivoire', 'Ivory silk scarf', 'وشاح حرير عاجي', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 260::numeric, null::numeric, false, false, false, false),
('collier-perle-or', 'DOS-014', 'accessoires', 'Collier perle & or', 'Pearl & gold necklace', 'قلادة لؤلؤ ذهبية', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 340::numeric, null::numeric, false, true, false, false),
('lunettes-diva', 'DOS-015', 'accessoires', 'Lunettes de soleil Diva', 'Diva sunglasses', 'نظارات شمسية ديفا', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 380::numeric, null::numeric, false, false, true, false),
('ceinture-cuir-gold', 'DOS-016', 'accessoires', 'Ceinture cuir Gold', 'Gold leather belt', 'حزام جلدي ذهبي', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 290::numeric, 230::numeric, false, false, false, true),
('sacs-a-dos-atlas', 'DOS-017', 'sacs-a-dos', 'Sac à dos Atlas', 'Backpack Atlas', 'حقيبة ظهر Atlas', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 79::numeric, null::numeric, false, false, false, false),
('sacs-a-dos-medina', 'DOS-018', 'sacs-a-dos', 'Sac à dos Médina', 'Backpack Médina', 'حقيبة ظهر Médina', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 199::numeric, null::numeric, false, false, true, false),
('sacs-a-dos-oasis', 'DOS-019', 'sacs-a-dos', 'Sac à dos Oasis', 'Backpack Oasis', 'حقيبة ظهر Oasis', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 499::numeric, 399::numeric, false, false, false, true),
('sacs-a-dos-rivage', 'DOS-020', 'sacs-a-dos', 'Sac à dos Rivage', 'Backpack Rivage', 'حقيبة ظهر Rivage', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 99::numeric, null::numeric, false, false, false, true),
('sacs-a-dos-kasbah', 'DOS-021', 'sacs-a-dos', 'Sac à dos Kasbah', 'Backpack Kasbah', 'حقيبة ظهر Kasbah', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 249::numeric, null::numeric, true, true, false, false),
('sacs-a-dos-nomade', 'DOS-022', 'sacs-a-dos', 'Sac à dos Nomade', 'Backpack Nomade', 'حقيبة ظهر Nomade', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 599::numeric, null::numeric, true, false, true, false),
('sacs-a-dos-aquarelle', 'DOS-023', 'sacs-a-dos', 'Sac à dos Aquarelle', 'Backpack Aquarelle', 'حقيبة ظهر Aquarelle', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 129::numeric, null::numeric, false, false, false, false),
('sacs-a-dos-soleil', 'DOS-024', 'sacs-a-dos', 'Sac à dos Soleil', 'Backpack Soleil', 'حقيبة ظهر Soleil', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 299::numeric, null::numeric, false, false, false, false),
('sacs-a-dos-jardin', 'DOS-025', 'sacs-a-dos', 'Sac à dos Jardin', 'Backpack Jardin', 'حقيبة ظهر Jardin', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 699::numeric, null::numeric, false, false, true, false),
('sacs-a-dos-majorelle', 'DOS-026', 'sacs-a-dos', 'Sac à dos Majorelle', 'Backpack Majorelle', 'حقيبة ظهر Majorelle', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 149::numeric, 119::numeric, false, true, false, true),
('sacs-a-dos-dune', 'DOS-027', 'sacs-a-dos', 'Sac à dos Dune', 'Backpack Dune', 'حقيبة ظهر Dune', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 349::numeric, null::numeric, false, false, false, true),
('sacs-a-dos-emeraude', 'DOS-028', 'sacs-a-dos', 'Sac à dos Émeraude', 'Backpack Émeraude', 'حقيبة ظهر Émeraude', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 799::numeric, null::numeric, true, true, false, false),
('sacs-a-dos-serenite', 'DOS-029', 'sacs-a-dos', 'Sac à dos Sérénité', 'Backpack Sérénité', 'حقيبة ظهر Sérénité', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 179::numeric, null::numeric, true, false, true, false),
('sacs-a-dos-palmier', 'DOS-030', 'sacs-a-dos', 'Sac à dos Palmier', 'Backpack Palmier', 'حقيبة ظهر Palmier', 'Cuir premium, doublure soignée et fermoir doré.', 'Premium finish, neat lining and golden clasp.', 'تشطيب فاخر وبطانة أنيقة وإغلاق ذهبي.', 399::numeric, null::numeric, false, false, false, false),
('baskets-cedre', 'DOS-031', 'baskets', 'Baskets Cèdre', 'Sneakers Cèdre', 'حذاء رياضي Cèdre', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 99::numeric, null::numeric, false, false, false, false),
('baskets-casablanca', 'DOS-032', 'baskets', 'Baskets Casablanca', 'Sneakers Casablanca', 'حذاء رياضي Casablanca', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 249::numeric, null::numeric, false, false, true, false),
('baskets-nuage', 'DOS-033', 'baskets', 'Baskets Nuage', 'Sneakers Nuage', 'حذاء رياضي Nuage', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 599::numeric, 479::numeric, false, false, false, true),
('baskets-luna', 'DOS-034', 'baskets', 'Baskets Luna', 'Sneakers Luna', 'حذاء رياضي Luna', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 129::numeric, null::numeric, false, false, false, true),
('baskets-eclipse', 'DOS-035', 'baskets', 'Baskets Éclipse', 'Sneakers Éclipse', 'حذاء رياضي Éclipse', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 299::numeric, null::numeric, true, true, false, false),
('baskets-avenue', 'DOS-036', 'baskets', 'Baskets Avenue', 'Sneakers Avenue', 'حذاء رياضي Avenue', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 699::numeric, null::numeric, true, false, true, false),
('baskets-lumiere', 'DOS-037', 'baskets', 'Baskets Lumière', 'Sneakers Lumière', 'حذاء رياضي Lumière', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 149::numeric, null::numeric, false, false, false, false),
('baskets-etoile', 'DOS-038', 'baskets', 'Baskets Étoile', 'Sneakers Étoile', 'حذاء رياضي Étoile', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 349::numeric, null::numeric, false, false, false, false),
('baskets-saphir', 'DOS-039', 'baskets', 'Baskets Saphir', 'Sneakers Saphir', 'حذاء رياضي Saphir', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 799::numeric, null::numeric, false, false, true, false),
('baskets-nacre', 'DOS-040', 'baskets', 'Baskets Nacré', 'Sneakers Nacré', 'حذاء رياضي Nacré', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 179::numeric, 143::numeric, false, true, false, true),
('baskets-mistral', 'DOS-041', 'baskets', 'Baskets Mistral', 'Sneakers Mistral', 'حذاء رياضي Mistral', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 399::numeric, null::numeric, false, false, false, true),
('baskets-velours', 'DOS-042', 'baskets', 'Baskets Velours', 'Sneakers Velours', 'حذاء رياضي Velours', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 79::numeric, null::numeric, true, true, false, false),
('baskets-cobalt', 'DOS-043', 'baskets', 'Baskets Cobalt', 'Sneakers Cobalt', 'حذاء رياضي Cobalt', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 199::numeric, null::numeric, true, false, true, false),
('baskets-sahara', 'DOS-044', 'baskets', 'Baskets Sahara', 'Sneakers Sahara', 'حذاء رياضي Sahara', 'Semelle confortable et finitions élégantes.', 'Comfortable sole and elegant finishing.', 'نعل مريح وتشطيبات أنيقة.', 499::numeric, null::numeric, false, false, false, false),
('chemisiers-nour', 'DOS-045', 'chemisiers', 'Chemisier Nour', 'Blouse Nour', 'بلوزة Nour', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 129::numeric, null::numeric, false, false, false, false),
('chemisiers-lina', 'DOS-046', 'chemisiers', 'Chemisier Lina', 'Blouse Lina', 'بلوزة Lina', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 299::numeric, null::numeric, false, false, true, false),
('chemisiers-yasmine', 'DOS-047', 'chemisiers', 'Chemisier Yasmine', 'Blouse Yasmine', 'بلوزة Yasmine', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 699::numeric, 559::numeric, false, false, false, true),
('chemisiers-salma', 'DOS-048', 'chemisiers', 'Chemisier Salma', 'Blouse Salma', 'بلوزة Salma', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 149::numeric, null::numeric, false, false, false, true),
('chemisiers-ines', 'DOS-049', 'chemisiers', 'Chemisier Inès', 'Blouse Inès', 'بلوزة Inès', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 349::numeric, null::numeric, true, true, false, false),
('chemisiers-maya', 'DOS-050', 'chemisiers', 'Chemisier Maya', 'Blouse Maya', 'بلوزة Maya', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 799::numeric, null::numeric, true, false, true, false),
('chemisiers-amira', 'DOS-051', 'chemisiers', 'Chemisier Amira', 'Blouse Amira', 'بلوزة Amira', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 179::numeric, null::numeric, false, false, false, false),
('chemisiers-leila', 'DOS-052', 'chemisiers', 'Chemisier Leïla', 'Blouse Leïla', 'بلوزة Leïla', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 399::numeric, null::numeric, false, false, false, false),
('chemisiers-sofia', 'DOS-053', 'chemisiers', 'Chemisier Sofia', 'Blouse Sofia', 'بلوزة Sofia', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 79::numeric, null::numeric, false, false, true, false),
('chemisiers-dalia', 'DOS-054', 'chemisiers', 'Chemisier Dalia', 'Blouse Dalia', 'بلوزة Dalia', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 199::numeric, 159::numeric, false, true, false, true),
('chemisiers-mina', 'DOS-055', 'chemisiers', 'Chemisier Mina', 'Blouse Mina', 'بلوزة Mina', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 499::numeric, null::numeric, false, false, false, true),
('chemisiers-aya', 'DOS-056', 'chemisiers', 'Chemisier Aya', 'Blouse Aya', 'بلوزة Aya', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 99::numeric, null::numeric, true, true, false, false),
('chemisiers-nadia', 'DOS-057', 'chemisiers', 'Chemisier Nadia', 'Blouse Nadia', 'بلوزة Nadia', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 249::numeric, null::numeric, true, false, true, false),
('chemisiers-zina', 'DOS-058', 'chemisiers', 'Chemisier Zina', 'Blouse Zina', 'بلوزة Zina', 'Coupe fluide, tombé impeccable, confort toute la journée.', 'Fluid cut, impeccable drape, all-day comfort.', 'قصّة انسيابية وسقوط مثالي وراحة طوال اليوم.', 599::numeric, null::numeric, false, false, false, false),
('bijoux-lilas', 'DOS-059', 'bijoux', 'Bijou Lilas', 'Jewelry piece Lilas', 'قطعة مجوهرات Lilas', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 149::numeric, null::numeric, false, false, false, false),
('bijoux-ambre', 'DOS-060', 'bijoux', 'Bijou Ambre', 'Jewelry piece Ambre', 'قطعة مجوهرات Ambre', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 349::numeric, null::numeric, false, false, true, false),
('bijoux-perle', 'DOS-061', 'bijoux', 'Bijou Perle', 'Jewelry piece Perle', 'قطعة مجوهرات Perle', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 799::numeric, 639::numeric, false, false, false, true),
('bijoux-eclat', 'DOS-062', 'bijoux', 'Bijou Éclat', 'Jewelry piece Éclat', 'قطعة مجوهرات Éclat', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 179::numeric, null::numeric, false, false, false, true),
('bijoux-aube', 'DOS-063', 'bijoux', 'Bijou Aube', 'Jewelry piece Aube', 'قطعة مجوهرات Aube', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 399::numeric, null::numeric, true, true, false, false),
('bijoux-jasmin', 'DOS-064', 'bijoux', 'Bijou Jasmin', 'Jewelry piece Jasmin', 'قطعة مجوهرات Jasmin', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 79::numeric, null::numeric, true, false, true, false),
('bijoux-rubis', 'DOS-065', 'bijoux', 'Bijou Rubis', 'Jewelry piece Rubis', 'قطعة مجوهرات Rubis', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 199::numeric, null::numeric, false, false, false, false),
('bijoux-opale', 'DOS-066', 'bijoux', 'Bijou Opale', 'Jewelry piece Opale', 'قطعة مجوهرات Opale', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 499::numeric, null::numeric, false, false, false, false),
('bijoux-tendresse', 'DOS-067', 'bijoux', 'Bijou Tendresse', 'Jewelry piece Tendresse', 'قطعة مجوهرات Tendresse', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 99::numeric, null::numeric, false, false, true, false),
('bijoux-flora', 'DOS-068', 'bijoux', 'Bijou Flora', 'Jewelry piece Flora', 'قطعة مجوهرات Flora', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 249::numeric, 199::numeric, false, true, false, true),
('bijoux-dahlia', 'DOS-069', 'bijoux', 'Bijou Dahlia', 'Jewelry piece Dahlia', 'قطعة مجوهرات Dahlia', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 599::numeric, null::numeric, false, false, false, true),
('bijoux-etoile', 'DOS-070', 'bijoux', 'Bijou Étoile', 'Jewelry piece Étoile', 'قطعة مجوهرات Étoile', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 129::numeric, null::numeric, true, true, false, false),
('bijoux-miel', 'DOS-071', 'bijoux', 'Bijou Miel', 'Jewelry piece Miel', 'قطعة مجوهرات Miel', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 299::numeric, null::numeric, true, false, true, false),
('bijoux-reve', 'DOS-072', 'bijoux', 'Bijou Rêve', 'Jewelry piece Rêve', 'قطعة مجوهرات Rêve', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 699::numeric, null::numeric, false, false, false, false),
('soins-visage-argan-doux', 'DOS-073', 'soins-visage', 'Soin visage Argan doux', 'Face care Argan doux', 'عناية بالوجه Argan doux', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 179::numeric, null::numeric, false, false, false, false),
('soins-visage-rose-de-fes', 'DOS-074', 'soins-visage', 'Soin visage Rose de Fès', 'Face care Rose de Fès', 'عناية بالوجه Rose de Fès', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 399::numeric, null::numeric, false, false, true, false),
('soins-visage-fleur-d-oranger', 'DOS-075', 'soins-visage', 'Soin visage Fleur d’oranger', 'Face care Fleur d’oranger', 'عناية بالوجه Fleur d’oranger', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 79::numeric, 63::numeric, false, false, false, true),
('soins-visage-lait-d-amande', 'DOS-076', 'soins-visage', 'Soin visage Lait d’amande', 'Face care Lait d’amande', 'عناية بالوجه Lait d’amande', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 199::numeric, null::numeric, false, false, false, true),
('soins-visage-neroli', 'DOS-077', 'soins-visage', 'Soin visage Néroli', 'Face care Néroli', 'عناية بالوجه Néroli', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 499::numeric, null::numeric, true, true, false, false),
('soins-visage-miel-pur', 'DOS-078', 'soins-visage', 'Soin visage Miel pur', 'Face care Miel pur', 'عناية بالوجه Miel pur', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 99::numeric, null::numeric, true, false, true, false),
('soins-visage-jasmin-blanc', 'DOS-079', 'soins-visage', 'Soin visage Jasmin blanc', 'Face care Jasmin blanc', 'عناية بالوجه Jasmin blanc', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 249::numeric, null::numeric, false, false, false, false),
('soins-visage-aloe-vera', 'DOS-080', 'soins-visage', 'Soin visage Aloe vera', 'Face care Aloe vera', 'عناية بالوجه Aloe vera', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 599::numeric, null::numeric, false, false, false, false),
('soins-visage-grenade', 'DOS-081', 'soins-visage', 'Soin visage Grenade', 'Face care Grenade', 'عناية بالوجه Grenade', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 129::numeric, null::numeric, false, false, true, false),
('soins-visage-eau-de-rose', 'DOS-082', 'soins-visage', 'Soin visage Eau de rose', 'Face care Eau de rose', 'عناية بالوجه Eau de rose', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 299::numeric, 239::numeric, false, true, false, true),
('soins-visage-lavande', 'DOS-083', 'soins-visage', 'Soin visage Lavande', 'Face care Lavande', 'عناية بالوجه Lavande', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 699::numeric, null::numeric, false, false, false, true),
('soins-visage-karite', 'DOS-084', 'soins-visage', 'Soin visage Karité', 'Face care Karité', 'عناية بالوجه Karité', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 149::numeric, null::numeric, true, true, false, false),
('soins-visage-verveine', 'DOS-085', 'soins-visage', 'Soin visage Verveine', 'Face care Verveine', 'عناية بالوجه Verveine', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 349::numeric, null::numeric, true, false, true, false),
('soins-visage-rituel-atlas', 'DOS-086', 'soins-visage', 'Soin visage Rituel Atlas', 'Face care Rituel Atlas', 'عناية بالوجه Rituel Atlas', 'Savon artisanal doux, formulé avec des ingrédients naturels.', 'Gentle artisanal soap made with natural ingredients.', 'صابون حرفي لطيف بمكونات طبيعية.', 799::numeric, null::numeric, false, false, false, false),
('decoration-zellige', 'DOS-087', 'decoration', 'Décoration Zellige', 'Home decor Zellige', 'قطعة ديكور Zellige', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 199::numeric, null::numeric, false, false, false, false),
('decoration-tanger', 'DOS-088', 'decoration', 'Décoration Tanger', 'Home decor Tanger', 'قطعة ديكور Tanger', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 499::numeric, null::numeric, false, false, true, false),
('decoration-marrakech', 'DOS-089', 'decoration', 'Décoration Marrakech', 'Home decor Marrakech', 'قطعة ديكور Marrakech', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 99::numeric, 79::numeric, false, false, false, true),
('decoration-essaouira', 'DOS-090', 'decoration', 'Décoration Essaouira', 'Home decor Essaouira', 'قطعة ديكور Essaouira', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 249::numeric, null::numeric, false, false, false, true),
('decoration-babouche', 'DOS-091', 'decoration', 'Décoration Babouche', 'Home decor Babouche', 'قطعة ديكور Babouche', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 599::numeric, null::numeric, true, true, false, false),
('decoration-safi', 'DOS-092', 'decoration', 'Décoration Safi', 'Home decor Safi', 'قطعة ديكور Safi', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 129::numeric, null::numeric, true, false, true, false),
('decoration-fes', 'DOS-093', 'decoration', 'Décoration Fès', 'Home decor Fès', 'قطعة ديكور Fès', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 299::numeric, null::numeric, false, false, false, false),
('decoration-andalousie', 'DOS-094', 'decoration', 'Décoration Andalousie', 'Home decor Andalousie', 'قطعة ديكور Andalousie', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 699::numeric, null::numeric, false, false, false, false),
('decoration-mosaique', 'DOS-095', 'decoration', 'Décoration Mosaïque', 'Home decor Mosaïque', 'قطعة ديكور Mosaïque', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 149::numeric, null::numeric, false, false, true, false),
('decoration-riad', 'DOS-096', 'decoration', 'Décoration Riad', 'Home decor Riad', 'قطعة ديكور Riad', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 349::numeric, 279::numeric, false, true, false, true),
('decoration-safran', 'DOS-097', 'decoration', 'Décoration Safran', 'Home decor Safran', 'قطعة ديكور Safran', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 799::numeric, null::numeric, false, false, false, true),
('decoration-tadelakt', 'DOS-098', 'decoration', 'Décoration Tadelakt', 'Home decor Tadelakt', 'قطعة ديكور Tadelakt', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 179::numeric, null::numeric, true, true, false, false),
('decoration-moucharabieh', 'DOS-099', 'decoration', 'Décoration Moucharabieh', 'Home decor Moucharabieh', 'قطعة ديكور Moucharabieh', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 399::numeric, null::numeric, true, false, true, false),
('decoration-dar', 'DOS-100', 'decoration', 'Décoration Dar', 'Home decor Dar', 'قطعة ديكور Dar', 'Un accessoire raffiné pour compléter votre allure.', 'A refined accessory to complete your look.', 'إكسسوار راقٍ يكمل إطلالتك.', 79::numeric, null::numeric, false, false, false, false)
) as v(slug, sku, cat, fr, en, ar, dfr, den, dar, price, sale, f, p, n, s) join public.categories c on c.slug = v.cat on conflict do nothing;

insert into public.product_images (product_id, url, alt, sort_order)
select p.id, v.url, p.name_fr, v.o from (values
('sac-riviera', 'DOS-001', '/demo/sac-riviera.svg', 0),
('sac-riviera', 'DOS-001', '/demo/sac-riviera-2.svg', 1),
('sac-bandouliere-aurore', 'DOS-002', '/demo/sac-bandouliere-aurore.svg', 0),
('sac-bandouliere-aurore', 'DOS-002', '/demo/sac-bandouliere-aurore-2.svg', 1),
('cabas-signature', 'DOS-003', '/demo/cabas-signature.svg', 0),
('cabas-signature', 'DOS-003', '/demo/cabas-signature-2.svg', 1),
('robe-satin-soraya', 'DOS-004', '/demo/robe-satin-soraya.svg', 0),
('robe-satin-soraya', 'DOS-004', '/demo/robe-satin-soraya-2.svg', 1),
('abaya-elegance', 'DOS-005', '/demo/abaya-elegance.svg', 0),
('abaya-elegance', 'DOS-005', '/demo/abaya-elegance-2.svg', 1),
('chemise-lin-nadia', 'DOS-006', '/demo/chemise-lin-nadia.svg', 0),
('chemise-lin-nadia', 'DOS-006', '/demo/chemise-lin-nadia-2.svg', 1),
('escarpins-velours', 'DOS-007', '/demo/escarpins-velours.svg', 0),
('escarpins-velours', 'DOS-007', '/demo/escarpins-velours-2.svg', 1),
('sandales-dorees-mira', 'DOS-008', '/demo/sandales-dorees-mira.svg', 0),
('sandales-dorees-mira', 'DOS-008', '/demo/sandales-dorees-mira-2.svg', 1),
('baskets-creme', 'DOS-009', '/demo/baskets-creme.svg', 0),
('baskets-creme', 'DOS-009', '/demo/baskets-creme-2.svg', 1),
('savon-rose-argan', 'DOS-010', '/demo/savon-rose-argan.svg', 0),
('savon-rose-argan', 'DOS-010', '/demo/savon-rose-argan-2.svg', 1),
('savon-noir-beldi', 'DOS-011', '/demo/savon-noir-beldi.svg', 0),
('savon-noir-beldi', 'DOS-011', '/demo/savon-noir-beldi-2.svg', 1),
('coffret-savons-dossora', 'DOS-012', '/demo/coffret-savons-dossora.svg', 0),
('coffret-savons-dossora', 'DOS-012', '/demo/coffret-savons-dossora-2.svg', 1),
('foulard-soie-ivoire', 'DOS-013', '/demo/foulard-soie-ivoire.svg', 0),
('foulard-soie-ivoire', 'DOS-013', '/demo/foulard-soie-ivoire-2.svg', 1),
('collier-perle-or', 'DOS-014', '/demo/collier-perle-or.svg', 0),
('collier-perle-or', 'DOS-014', '/demo/collier-perle-or-2.svg', 1),
('lunettes-diva', 'DOS-015', '/demo/lunettes-diva.svg', 0),
('lunettes-diva', 'DOS-015', '/demo/lunettes-diva-2.svg', 1),
('ceinture-cuir-gold', 'DOS-016', '/demo/ceinture-cuir-gold.svg', 0),
('ceinture-cuir-gold', 'DOS-016', '/demo/ceinture-cuir-gold-2.svg', 1),
('sacs-a-dos-atlas', 'DOS-017', '/demo/sacs-a-dos-atlas.svg', 0),
('sacs-a-dos-atlas', 'DOS-017', '/demo/sacs-a-dos-atlas-2.svg', 1),
('sacs-a-dos-medina', 'DOS-018', '/demo/sacs-a-dos-medina.svg', 0),
('sacs-a-dos-medina', 'DOS-018', '/demo/sacs-a-dos-medina-2.svg', 1),
('sacs-a-dos-oasis', 'DOS-019', '/demo/sacs-a-dos-oasis.svg', 0),
('sacs-a-dos-oasis', 'DOS-019', '/demo/sacs-a-dos-oasis-2.svg', 1),
('sacs-a-dos-rivage', 'DOS-020', '/demo/sacs-a-dos-rivage.svg', 0),
('sacs-a-dos-rivage', 'DOS-020', '/demo/sacs-a-dos-rivage-2.svg', 1),
('sacs-a-dos-kasbah', 'DOS-021', '/demo/sacs-a-dos-kasbah.svg', 0),
('sacs-a-dos-kasbah', 'DOS-021', '/demo/sacs-a-dos-kasbah-2.svg', 1),
('sacs-a-dos-nomade', 'DOS-022', '/demo/sacs-a-dos-nomade.svg', 0),
('sacs-a-dos-nomade', 'DOS-022', '/demo/sacs-a-dos-nomade-2.svg', 1),
('sacs-a-dos-aquarelle', 'DOS-023', '/demo/sacs-a-dos-aquarelle.svg', 0),
('sacs-a-dos-aquarelle', 'DOS-023', '/demo/sacs-a-dos-aquarelle-2.svg', 1),
('sacs-a-dos-soleil', 'DOS-024', '/demo/sacs-a-dos-soleil.svg', 0),
('sacs-a-dos-soleil', 'DOS-024', '/demo/sacs-a-dos-soleil-2.svg', 1),
('sacs-a-dos-jardin', 'DOS-025', '/demo/sacs-a-dos-jardin.svg', 0),
('sacs-a-dos-jardin', 'DOS-025', '/demo/sacs-a-dos-jardin-2.svg', 1),
('sacs-a-dos-majorelle', 'DOS-026', '/demo/sacs-a-dos-majorelle.svg', 0),
('sacs-a-dos-majorelle', 'DOS-026', '/demo/sacs-a-dos-majorelle-2.svg', 1),
('sacs-a-dos-dune', 'DOS-027', '/demo/sacs-a-dos-dune.svg', 0),
('sacs-a-dos-dune', 'DOS-027', '/demo/sacs-a-dos-dune-2.svg', 1),
('sacs-a-dos-emeraude', 'DOS-028', '/demo/sacs-a-dos-emeraude.svg', 0),
('sacs-a-dos-emeraude', 'DOS-028', '/demo/sacs-a-dos-emeraude-2.svg', 1),
('sacs-a-dos-serenite', 'DOS-029', '/demo/sacs-a-dos-serenite.svg', 0),
('sacs-a-dos-serenite', 'DOS-029', '/demo/sacs-a-dos-serenite-2.svg', 1),
('sacs-a-dos-palmier', 'DOS-030', '/demo/sacs-a-dos-palmier.svg', 0),
('sacs-a-dos-palmier', 'DOS-030', '/demo/sacs-a-dos-palmier-2.svg', 1),
('baskets-cedre', 'DOS-031', '/demo/baskets-cedre.svg', 0),
('baskets-cedre', 'DOS-031', '/demo/baskets-cedre-2.svg', 1),
('baskets-casablanca', 'DOS-032', '/demo/baskets-casablanca.svg', 0),
('baskets-casablanca', 'DOS-032', '/demo/baskets-casablanca-2.svg', 1),
('baskets-nuage', 'DOS-033', '/demo/baskets-nuage.svg', 0),
('baskets-nuage', 'DOS-033', '/demo/baskets-nuage-2.svg', 1),
('baskets-luna', 'DOS-034', '/demo/baskets-luna.svg', 0),
('baskets-luna', 'DOS-034', '/demo/baskets-luna-2.svg', 1),
('baskets-eclipse', 'DOS-035', '/demo/baskets-eclipse.svg', 0),
('baskets-eclipse', 'DOS-035', '/demo/baskets-eclipse-2.svg', 1),
('baskets-avenue', 'DOS-036', '/demo/baskets-avenue.svg', 0),
('baskets-avenue', 'DOS-036', '/demo/baskets-avenue-2.svg', 1),
('baskets-lumiere', 'DOS-037', '/demo/baskets-lumiere.svg', 0),
('baskets-lumiere', 'DOS-037', '/demo/baskets-lumiere-2.svg', 1),
('baskets-etoile', 'DOS-038', '/demo/baskets-etoile.svg', 0),
('baskets-etoile', 'DOS-038', '/demo/baskets-etoile-2.svg', 1),
('baskets-saphir', 'DOS-039', '/demo/baskets-saphir.svg', 0),
('baskets-saphir', 'DOS-039', '/demo/baskets-saphir-2.svg', 1),
('baskets-nacre', 'DOS-040', '/demo/baskets-nacre.svg', 0),
('baskets-nacre', 'DOS-040', '/demo/baskets-nacre-2.svg', 1),
('baskets-mistral', 'DOS-041', '/demo/baskets-mistral.svg', 0),
('baskets-mistral', 'DOS-041', '/demo/baskets-mistral-2.svg', 1),
('baskets-velours', 'DOS-042', '/demo/baskets-velours.svg', 0),
('baskets-velours', 'DOS-042', '/demo/baskets-velours-2.svg', 1),
('baskets-cobalt', 'DOS-043', '/demo/baskets-cobalt.svg', 0),
('baskets-cobalt', 'DOS-043', '/demo/baskets-cobalt-2.svg', 1),
('baskets-sahara', 'DOS-044', '/demo/baskets-sahara.svg', 0),
('baskets-sahara', 'DOS-044', '/demo/baskets-sahara-2.svg', 1),
('chemisiers-nour', 'DOS-045', '/demo/chemisiers-nour.svg', 0),
('chemisiers-nour', 'DOS-045', '/demo/chemisiers-nour-2.svg', 1),
('chemisiers-lina', 'DOS-046', '/demo/chemisiers-lina.svg', 0),
('chemisiers-lina', 'DOS-046', '/demo/chemisiers-lina-2.svg', 1),
('chemisiers-yasmine', 'DOS-047', '/demo/chemisiers-yasmine.svg', 0),
('chemisiers-yasmine', 'DOS-047', '/demo/chemisiers-yasmine-2.svg', 1),
('chemisiers-salma', 'DOS-048', '/demo/chemisiers-salma.svg', 0),
('chemisiers-salma', 'DOS-048', '/demo/chemisiers-salma-2.svg', 1),
('chemisiers-ines', 'DOS-049', '/demo/chemisiers-ines.svg', 0),
('chemisiers-ines', 'DOS-049', '/demo/chemisiers-ines-2.svg', 1),
('chemisiers-maya', 'DOS-050', '/demo/chemisiers-maya.svg', 0),
('chemisiers-maya', 'DOS-050', '/demo/chemisiers-maya-2.svg', 1),
('chemisiers-amira', 'DOS-051', '/demo/chemisiers-amira.svg', 0),
('chemisiers-amira', 'DOS-051', '/demo/chemisiers-amira-2.svg', 1),
('chemisiers-leila', 'DOS-052', '/demo/chemisiers-leila.svg', 0),
('chemisiers-leila', 'DOS-052', '/demo/chemisiers-leila-2.svg', 1),
('chemisiers-sofia', 'DOS-053', '/demo/chemisiers-sofia.svg', 0),
('chemisiers-sofia', 'DOS-053', '/demo/chemisiers-sofia-2.svg', 1),
('chemisiers-dalia', 'DOS-054', '/demo/chemisiers-dalia.svg', 0),
('chemisiers-dalia', 'DOS-054', '/demo/chemisiers-dalia-2.svg', 1),
('chemisiers-mina', 'DOS-055', '/demo/chemisiers-mina.svg', 0),
('chemisiers-mina', 'DOS-055', '/demo/chemisiers-mina-2.svg', 1),
('chemisiers-aya', 'DOS-056', '/demo/chemisiers-aya.svg', 0),
('chemisiers-aya', 'DOS-056', '/demo/chemisiers-aya-2.svg', 1),
('chemisiers-nadia', 'DOS-057', '/demo/chemisiers-nadia.svg', 0),
('chemisiers-nadia', 'DOS-057', '/demo/chemisiers-nadia-2.svg', 1),
('chemisiers-zina', 'DOS-058', '/demo/chemisiers-zina.svg', 0),
('chemisiers-zina', 'DOS-058', '/demo/chemisiers-zina-2.svg', 1),
('bijoux-lilas', 'DOS-059', '/demo/bijoux-lilas.svg', 0),
('bijoux-lilas', 'DOS-059', '/demo/bijoux-lilas-2.svg', 1),
('bijoux-ambre', 'DOS-060', '/demo/bijoux-ambre.svg', 0),
('bijoux-ambre', 'DOS-060', '/demo/bijoux-ambre-2.svg', 1),
('bijoux-perle', 'DOS-061', '/demo/bijoux-perle.svg', 0),
('bijoux-perle', 'DOS-061', '/demo/bijoux-perle-2.svg', 1),
('bijoux-eclat', 'DOS-062', '/demo/bijoux-eclat.svg', 0),
('bijoux-eclat', 'DOS-062', '/demo/bijoux-eclat-2.svg', 1),
('bijoux-aube', 'DOS-063', '/demo/bijoux-aube.svg', 0),
('bijoux-aube', 'DOS-063', '/demo/bijoux-aube-2.svg', 1),
('bijoux-jasmin', 'DOS-064', '/demo/bijoux-jasmin.svg', 0),
('bijoux-jasmin', 'DOS-064', '/demo/bijoux-jasmin-2.svg', 1),
('bijoux-rubis', 'DOS-065', '/demo/bijoux-rubis.svg', 0),
('bijoux-rubis', 'DOS-065', '/demo/bijoux-rubis-2.svg', 1),
('bijoux-opale', 'DOS-066', '/demo/bijoux-opale.svg', 0),
('bijoux-opale', 'DOS-066', '/demo/bijoux-opale-2.svg', 1),
('bijoux-tendresse', 'DOS-067', '/demo/bijoux-tendresse.svg', 0),
('bijoux-tendresse', 'DOS-067', '/demo/bijoux-tendresse-2.svg', 1),
('bijoux-flora', 'DOS-068', '/demo/bijoux-flora.svg', 0),
('bijoux-flora', 'DOS-068', '/demo/bijoux-flora-2.svg', 1),
('bijoux-dahlia', 'DOS-069', '/demo/bijoux-dahlia.svg', 0),
('bijoux-dahlia', 'DOS-069', '/demo/bijoux-dahlia-2.svg', 1),
('bijoux-etoile', 'DOS-070', '/demo/bijoux-etoile.svg', 0),
('bijoux-etoile', 'DOS-070', '/demo/bijoux-etoile-2.svg', 1),
('bijoux-miel', 'DOS-071', '/demo/bijoux-miel.svg', 0),
('bijoux-miel', 'DOS-071', '/demo/bijoux-miel-2.svg', 1),
('bijoux-reve', 'DOS-072', '/demo/bijoux-reve.svg', 0),
('bijoux-reve', 'DOS-072', '/demo/bijoux-reve-2.svg', 1),
('soins-visage-argan-doux', 'DOS-073', '/demo/soins-visage-argan-doux.svg', 0),
('soins-visage-argan-doux', 'DOS-073', '/demo/soins-visage-argan-doux-2.svg', 1),
('soins-visage-rose-de-fes', 'DOS-074', '/demo/soins-visage-rose-de-fes.svg', 0),
('soins-visage-rose-de-fes', 'DOS-074', '/demo/soins-visage-rose-de-fes-2.svg', 1),
('soins-visage-fleur-d-oranger', 'DOS-075', '/demo/soins-visage-fleur-d-oranger.svg', 0),
('soins-visage-fleur-d-oranger', 'DOS-075', '/demo/soins-visage-fleur-d-oranger-2.svg', 1),
('soins-visage-lait-d-amande', 'DOS-076', '/demo/soins-visage-lait-d-amande.svg', 0),
('soins-visage-lait-d-amande', 'DOS-076', '/demo/soins-visage-lait-d-amande-2.svg', 1),
('soins-visage-neroli', 'DOS-077', '/demo/soins-visage-neroli.svg', 0),
('soins-visage-neroli', 'DOS-077', '/demo/soins-visage-neroli-2.svg', 1),
('soins-visage-miel-pur', 'DOS-078', '/demo/soins-visage-miel-pur.svg', 0),
('soins-visage-miel-pur', 'DOS-078', '/demo/soins-visage-miel-pur-2.svg', 1),
('soins-visage-jasmin-blanc', 'DOS-079', '/demo/soins-visage-jasmin-blanc.svg', 0),
('soins-visage-jasmin-blanc', 'DOS-079', '/demo/soins-visage-jasmin-blanc-2.svg', 1),
('soins-visage-aloe-vera', 'DOS-080', '/demo/soins-visage-aloe-vera.svg', 0),
('soins-visage-aloe-vera', 'DOS-080', '/demo/soins-visage-aloe-vera-2.svg', 1),
('soins-visage-grenade', 'DOS-081', '/demo/soins-visage-grenade.svg', 0),
('soins-visage-grenade', 'DOS-081', '/demo/soins-visage-grenade-2.svg', 1),
('soins-visage-eau-de-rose', 'DOS-082', '/demo/soins-visage-eau-de-rose.svg', 0),
('soins-visage-eau-de-rose', 'DOS-082', '/demo/soins-visage-eau-de-rose-2.svg', 1),
('soins-visage-lavande', 'DOS-083', '/demo/soins-visage-lavande.svg', 0),
('soins-visage-lavande', 'DOS-083', '/demo/soins-visage-lavande-2.svg', 1),
('soins-visage-karite', 'DOS-084', '/demo/soins-visage-karite.svg', 0),
('soins-visage-karite', 'DOS-084', '/demo/soins-visage-karite-2.svg', 1),
('soins-visage-verveine', 'DOS-085', '/demo/soins-visage-verveine.svg', 0),
('soins-visage-verveine', 'DOS-085', '/demo/soins-visage-verveine-2.svg', 1),
('soins-visage-rituel-atlas', 'DOS-086', '/demo/soins-visage-rituel-atlas.svg', 0),
('soins-visage-rituel-atlas', 'DOS-086', '/demo/soins-visage-rituel-atlas-2.svg', 1),
('decoration-zellige', 'DOS-087', '/demo/decoration-zellige.svg', 0),
('decoration-zellige', 'DOS-087', '/demo/decoration-zellige-2.svg', 1),
('decoration-tanger', 'DOS-088', '/demo/decoration-tanger.svg', 0),
('decoration-tanger', 'DOS-088', '/demo/decoration-tanger-2.svg', 1),
('decoration-marrakech', 'DOS-089', '/demo/decoration-marrakech.svg', 0),
('decoration-marrakech', 'DOS-089', '/demo/decoration-marrakech-2.svg', 1),
('decoration-essaouira', 'DOS-090', '/demo/decoration-essaouira.svg', 0),
('decoration-essaouira', 'DOS-090', '/demo/decoration-essaouira-2.svg', 1),
('decoration-babouche', 'DOS-091', '/demo/decoration-babouche.svg', 0),
('decoration-babouche', 'DOS-091', '/demo/decoration-babouche-2.svg', 1),
('decoration-safi', 'DOS-092', '/demo/decoration-safi.svg', 0),
('decoration-safi', 'DOS-092', '/demo/decoration-safi-2.svg', 1),
('decoration-fes', 'DOS-093', '/demo/decoration-fes.svg', 0),
('decoration-fes', 'DOS-093', '/demo/decoration-fes-2.svg', 1),
('decoration-andalousie', 'DOS-094', '/demo/decoration-andalousie.svg', 0),
('decoration-andalousie', 'DOS-094', '/demo/decoration-andalousie-2.svg', 1),
('decoration-mosaique', 'DOS-095', '/demo/decoration-mosaique.svg', 0),
('decoration-mosaique', 'DOS-095', '/demo/decoration-mosaique-2.svg', 1),
('decoration-riad', 'DOS-096', '/demo/decoration-riad.svg', 0),
('decoration-riad', 'DOS-096', '/demo/decoration-riad-2.svg', 1),
('decoration-safran', 'DOS-097', '/demo/decoration-safran.svg', 0),
('decoration-safran', 'DOS-097', '/demo/decoration-safran-2.svg', 1),
('decoration-tadelakt', 'DOS-098', '/demo/decoration-tadelakt.svg', 0),
('decoration-tadelakt', 'DOS-098', '/demo/decoration-tadelakt-2.svg', 1),
('decoration-moucharabieh', 'DOS-099', '/demo/decoration-moucharabieh.svg', 0),
('decoration-moucharabieh', 'DOS-099', '/demo/decoration-moucharabieh-2.svg', 1),
('decoration-dar', 'DOS-100', '/demo/decoration-dar.svg', 0),
('decoration-dar', 'DOS-100', '/demo/decoration-dar-2.svg', 1)
) as v(slug, sku, url, o) join public.products p on p.slug = v.slug and p.sku = v.sku where not exists (select 1 from public.product_images i where i.product_id = p.id and i.url = v.url);

insert into public.product_variants (product_id, sku, color, size, shoe_size, stock, low_stock_threshold)
select p.id, v.sku, v.color, v.size, v.shoe, v.stock, 3 from (values
('sac-riviera', 'DOS-001', 'DOS-001-BO', 'Bordeaux', null, null, 4),
('sac-riviera', 'DOS-001', 'DOS-001-IV', 'Ivoire', null, null, 7),
('sac-bandouliere-aurore', 'DOS-002', 'DOS-002-OR', 'Or champagne', null, null, 11),
('sac-bandouliere-aurore', 'DOS-002', 'DOS-002-BO', 'Bordeaux', null, null, 14),
('cabas-signature', 'DOS-003', 'DOS-003-BO', 'Bordeaux nuit', null, null, 4),
('robe-satin-soraya', 'DOS-004', 'DOS-004-BO-S', 'Bordeaux', 'S', null, 12),
('robe-satin-soraya', 'DOS-004', 'DOS-004-BO-M', 'Bordeaux', 'M', null, 12),
('robe-satin-soraya', 'DOS-004', 'DOS-004-BO-L', 'Bordeaux', 'L', null, 12),
('robe-satin-soraya', 'DOS-004', 'DOS-004-BO-XL', 'Bordeaux', 'XL', null, 13),
('robe-satin-soraya', 'DOS-004', 'DOS-004-CH-S', 'Champagne', 'S', null, 15),
('robe-satin-soraya', 'DOS-004', 'DOS-004-CH-M', 'Champagne', 'M', null, 15),
('robe-satin-soraya', 'DOS-004', 'DOS-004-CH-L', 'Champagne', 'L', null, 15),
('robe-satin-soraya', 'DOS-004', 'DOS-004-CH-XL', 'Champagne', 'XL', null, 16),
('abaya-elegance', 'DOS-005', 'DOS-005-NO-S', 'Noir', 'S', null, 5),
('abaya-elegance', 'DOS-005', 'DOS-005-NO-M', 'Noir', 'M', null, 5),
('abaya-elegance', 'DOS-005', 'DOS-005-NO-L', 'Noir', 'L', null, 5),
('abaya-elegance', 'DOS-005', 'DOS-005-NO-XL', 'Noir', 'XL', null, 6),
('chemise-lin-nadia', 'DOS-006', 'DOS-006-SA-S', 'Sable', 'S', null, 12),
('chemise-lin-nadia', 'DOS-006', 'DOS-006-SA-M', 'Sable', 'M', null, 12),
('chemise-lin-nadia', 'DOS-006', 'DOS-006-SA-L', 'Sable', 'L', null, 12),
('chemise-lin-nadia', 'DOS-006', 'DOS-006-SA-XL', 'Sable', 'XL', null, 13),
('escarpins-velours', 'DOS-007', 'DOS-007-BO-37', 'Bordeaux', null, '37', 6),
('escarpins-velours', 'DOS-007', 'DOS-007-BO-38', 'Bordeaux', null, '38', 7),
('escarpins-velours', 'DOS-007', 'DOS-007-BO-39', 'Bordeaux', null, '39', 8),
('escarpins-velours', 'DOS-007', 'DOS-007-BO-40', 'Bordeaux', null, '40', 4),
('escarpins-velours', 'DOS-007', 'DOS-007-BO-41', 'Bordeaux', null, '41', 5),
('sandales-dorees-mira', 'DOS-008', 'DOS-008-DO-37', 'Doré', null, '37', 13),
('sandales-dorees-mira', 'DOS-008', 'DOS-008-DO-38', 'Doré', null, '38', 14),
('sandales-dorees-mira', 'DOS-008', 'DOS-008-DO-39', 'Doré', null, '39', 15),
('sandales-dorees-mira', 'DOS-008', 'DOS-008-DO-40', 'Doré', null, '40', 11),
('sandales-dorees-mira', 'DOS-008', 'DOS-008-DO-41', 'Doré', null, '41', 12),
('baskets-creme', 'DOS-009', 'DOS-009-CR-37', 'Crème', null, '37', 6),
('baskets-creme', 'DOS-009', 'DOS-009-CR-38', 'Crème', null, '38', 7),
('baskets-creme', 'DOS-009', 'DOS-009-CR-39', 'Crème', null, '39', 8),
('baskets-creme', 'DOS-009', 'DOS-009-CR-40', 'Crème', null, '40', 4),
('baskets-creme', 'DOS-009', 'DOS-009-CR-41', 'Crème', null, '41', 5),
('savon-rose-argan', 'DOS-010', 'DOS-010-RO', 'Rose', null, null, 11),
('savon-noir-beldi', 'DOS-011', 'DOS-011-NA', 'Naturel', null, null, 4),
('coffret-savons-dossora', 'DOS-012', 'DOS-012-CO', 'Coffret', null, null, 11),
('foulard-soie-ivoire', 'DOS-013', 'DOS-013-IV', 'Ivoire', null, null, 4),
('collier-perle-or', 'DOS-014', 'DOS-014-OR', 'Or', null, null, 11),
('lunettes-diva', 'DOS-015', 'DOS-015-NO', 'Noir', null, null, 4),
('ceinture-cuir-gold', 'DOS-016', 'DOS-016-BO', 'Bordeaux', null, null, 11),
('sacs-a-dos-atlas', 'DOS-017', 'DOS-017-BO', 'Bordeaux', null, null, 0),
('sacs-a-dos-medina', 'DOS-018', 'DOS-018-OR', 'Or champagne', null, null, 2),
('sacs-a-dos-oasis', 'DOS-019', 'DOS-019-SA', 'Sable', null, null, 7),
('sacs-a-dos-rivage', 'DOS-020', 'DOS-020-BO', 'Bordeaux nuit', null, null, 8),
('sacs-a-dos-kasbah', 'DOS-021', 'DOS-021-RO', 'Rose', null, null, 9),
('sacs-a-dos-nomade', 'DOS-022', 'DOS-022-NO', 'Noir', null, null, 10),
('sacs-a-dos-aquarelle', 'DOS-023', 'DOS-023-MA', 'Marron', null, null, 11),
('sacs-a-dos-soleil', 'DOS-024', 'DOS-024-BO', 'Bordeaux', null, null, 12),
('sacs-a-dos-jardin', 'DOS-025', 'DOS-025-OR', 'Or champagne', null, null, 13),
('sacs-a-dos-majorelle', 'DOS-026', 'DOS-026-SA', 'Sable', null, null, 14),
('sacs-a-dos-dune', 'DOS-027', 'DOS-027-BO', 'Bordeaux nuit', null, null, 15),
('sacs-a-dos-emeraude', 'DOS-028', 'DOS-028-RO', 'Rose', null, null, 1),
('sacs-a-dos-serenite', 'DOS-029', 'DOS-029-NO', 'Noir', null, null, 2),
('sacs-a-dos-palmier', 'DOS-030', 'DOS-030-MA', 'Marron', null, null, 5),
('baskets-cedre', 'DOS-031', 'DOS-031-BO-37', 'Bordeaux', null, '37', 6),
('baskets-cedre', 'DOS-031', 'DOS-031-BO-38', 'Bordeaux', null, '38', 6),
('baskets-cedre', 'DOS-031', 'DOS-031-BO-39', 'Bordeaux', null, '39', 6),
('baskets-cedre', 'DOS-031', 'DOS-031-BO-40', 'Bordeaux', null, '40', 6),
('baskets-cedre', 'DOS-031', 'DOS-031-BO-41', 'Bordeaux', null, '41', 6),
('baskets-casablanca', 'DOS-032', 'DOS-032-OR-37', 'Or champagne', null, '37', 7),
('baskets-casablanca', 'DOS-032', 'DOS-032-OR-38', 'Or champagne', null, '38', 7),
('baskets-casablanca', 'DOS-032', 'DOS-032-OR-39', 'Or champagne', null, '39', 7),
('baskets-casablanca', 'DOS-032', 'DOS-032-OR-40', 'Or champagne', null, '40', 7),
('baskets-casablanca', 'DOS-032', 'DOS-032-OR-41', 'Or champagne', null, '41', 7),
('baskets-nuage', 'DOS-033', 'DOS-033-SA-37', 'Sable', null, '37', 8),
('baskets-nuage', 'DOS-033', 'DOS-033-SA-38', 'Sable', null, '38', 8),
('baskets-nuage', 'DOS-033', 'DOS-033-SA-39', 'Sable', null, '39', 8),
('baskets-nuage', 'DOS-033', 'DOS-033-SA-40', 'Sable', null, '40', 8),
('baskets-nuage', 'DOS-033', 'DOS-033-SA-41', 'Sable', null, '41', 8),
('baskets-luna', 'DOS-034', 'DOS-034-BO-37', 'Bordeaux nuit', null, '37', 9),
('baskets-luna', 'DOS-034', 'DOS-034-BO-38', 'Bordeaux nuit', null, '38', 9),
('baskets-luna', 'DOS-034', 'DOS-034-BO-39', 'Bordeaux nuit', null, '39', 9),
('baskets-luna', 'DOS-034', 'DOS-034-BO-40', 'Bordeaux nuit', null, '40', 9),
('baskets-luna', 'DOS-034', 'DOS-034-BO-41', 'Bordeaux nuit', null, '41', 9),
('baskets-eclipse', 'DOS-035', 'DOS-035-RO-37', 'Rose', null, '37', 10),
('baskets-eclipse', 'DOS-035', 'DOS-035-RO-38', 'Rose', null, '38', 10),
('baskets-eclipse', 'DOS-035', 'DOS-035-RO-39', 'Rose', null, '39', 10),
('baskets-eclipse', 'DOS-035', 'DOS-035-RO-40', 'Rose', null, '40', 10),
('baskets-eclipse', 'DOS-035', 'DOS-035-RO-41', 'Rose', null, '41', 10),
('baskets-avenue', 'DOS-036', 'DOS-036-NO-37', 'Noir', null, '37', 0),
('baskets-avenue', 'DOS-036', 'DOS-036-NO-38', 'Noir', null, '38', 0),
('baskets-avenue', 'DOS-036', 'DOS-036-NO-39', 'Noir', null, '39', 0),
('baskets-avenue', 'DOS-036', 'DOS-036-NO-40', 'Noir', null, '40', 0),
('baskets-avenue', 'DOS-036', 'DOS-036-NO-41', 'Noir', null, '41', 0),
('baskets-lumiere', 'DOS-037', 'DOS-037-MA-37', 'Marron', null, '37', 12),
('baskets-lumiere', 'DOS-037', 'DOS-037-MA-38', 'Marron', null, '38', 12),
('baskets-lumiere', 'DOS-037', 'DOS-037-MA-39', 'Marron', null, '39', 12),
('baskets-lumiere', 'DOS-037', 'DOS-037-MA-40', 'Marron', null, '40', 12),
('baskets-lumiere', 'DOS-037', 'DOS-037-MA-41', 'Marron', null, '41', 12),
('baskets-etoile', 'DOS-038', 'DOS-038-BO-37', 'Bordeaux', null, '37', 13),
('baskets-etoile', 'DOS-038', 'DOS-038-BO-38', 'Bordeaux', null, '38', 13),
('baskets-etoile', 'DOS-038', 'DOS-038-BO-39', 'Bordeaux', null, '39', 13),
('baskets-etoile', 'DOS-038', 'DOS-038-BO-40', 'Bordeaux', null, '40', 13),
('baskets-etoile', 'DOS-038', 'DOS-038-BO-41', 'Bordeaux', null, '41', 13),
('baskets-saphir', 'DOS-039', 'DOS-039-OR-37', 'Or champagne', null, '37', 1),
('baskets-saphir', 'DOS-039', 'DOS-039-OR-38', 'Or champagne', null, '38', 1),
('baskets-saphir', 'DOS-039', 'DOS-039-OR-39', 'Or champagne', null, '39', 1),
('baskets-saphir', 'DOS-039', 'DOS-039-OR-40', 'Or champagne', null, '40', 1),
('baskets-saphir', 'DOS-039', 'DOS-039-OR-41', 'Or champagne', null, '41', 1),
('baskets-nacre', 'DOS-040', 'DOS-040-SA-37', 'Sable', null, '37', 2),
('baskets-nacre', 'DOS-040', 'DOS-040-SA-38', 'Sable', null, '38', 2),
('baskets-nacre', 'DOS-040', 'DOS-040-SA-39', 'Sable', null, '39', 2),
('baskets-nacre', 'DOS-040', 'DOS-040-SA-40', 'Sable', null, '40', 2),
('baskets-nacre', 'DOS-040', 'DOS-040-SA-41', 'Sable', null, '41', 2),
('baskets-mistral', 'DOS-041', 'DOS-041-BO-37', 'Bordeaux nuit', null, '37', 16),
('baskets-mistral', 'DOS-041', 'DOS-041-BO-38', 'Bordeaux nuit', null, '38', 16),
('baskets-mistral', 'DOS-041', 'DOS-041-BO-39', 'Bordeaux nuit', null, '39', 16),
('baskets-mistral', 'DOS-041', 'DOS-041-BO-40', 'Bordeaux nuit', null, '40', 16),
('baskets-mistral', 'DOS-041', 'DOS-041-BO-41', 'Bordeaux nuit', null, '41', 16),
('baskets-velours', 'DOS-042', 'DOS-042-RO-37', 'Rose', null, '37', 17),
('baskets-velours', 'DOS-042', 'DOS-042-RO-38', 'Rose', null, '38', 17),
('baskets-velours', 'DOS-042', 'DOS-042-RO-39', 'Rose', null, '39', 17),
('baskets-velours', 'DOS-042', 'DOS-042-RO-40', 'Rose', null, '40', 17),
('baskets-velours', 'DOS-042', 'DOS-042-RO-41', 'Rose', null, '41', 17),
('baskets-cobalt', 'DOS-043', 'DOS-043-NO-37', 'Noir', null, '37', 5),
('baskets-cobalt', 'DOS-043', 'DOS-043-NO-38', 'Noir', null, '38', 5),
('baskets-cobalt', 'DOS-043', 'DOS-043-NO-39', 'Noir', null, '39', 5),
('baskets-cobalt', 'DOS-043', 'DOS-043-NO-40', 'Noir', null, '40', 5),
('baskets-cobalt', 'DOS-043', 'DOS-043-NO-41', 'Noir', null, '41', 5),
('baskets-sahara', 'DOS-044', 'DOS-044-MA-37', 'Marron', null, '37', 6),
('baskets-sahara', 'DOS-044', 'DOS-044-MA-38', 'Marron', null, '38', 6),
('baskets-sahara', 'DOS-044', 'DOS-044-MA-39', 'Marron', null, '39', 6),
('baskets-sahara', 'DOS-044', 'DOS-044-MA-40', 'Marron', null, '40', 6),
('baskets-sahara', 'DOS-044', 'DOS-044-MA-41', 'Marron', null, '41', 6),
('chemisiers-nour', 'DOS-045', 'DOS-045-BO-S', 'Bordeaux', 'S', null, 7),
('chemisiers-nour', 'DOS-045', 'DOS-045-BO-M', 'Bordeaux', 'M', null, 7),
('chemisiers-nour', 'DOS-045', 'DOS-045-BO-L', 'Bordeaux', 'L', null, 7),
('chemisiers-nour', 'DOS-045', 'DOS-045-BO-XL', 'Bordeaux', 'XL', null, 7),
('chemisiers-lina', 'DOS-046', 'DOS-046-OR-S', 'Or champagne', 'S', null, 8),
('chemisiers-lina', 'DOS-046', 'DOS-046-OR-M', 'Or champagne', 'M', null, 8),
('chemisiers-lina', 'DOS-046', 'DOS-046-OR-L', 'Or champagne', 'L', null, 8),
('chemisiers-lina', 'DOS-046', 'DOS-046-OR-XL', 'Or champagne', 'XL', null, 8),
('chemisiers-yasmine', 'DOS-047', 'DOS-047-SA-S', 'Sable', 'S', null, 9),
('chemisiers-yasmine', 'DOS-047', 'DOS-047-SA-M', 'Sable', 'M', null, 9),
('chemisiers-yasmine', 'DOS-047', 'DOS-047-SA-L', 'Sable', 'L', null, 9),
('chemisiers-yasmine', 'DOS-047', 'DOS-047-SA-XL', 'Sable', 'XL', null, 9),
('chemisiers-salma', 'DOS-048', 'DOS-048-BO-S', 'Bordeaux nuit', 'S', null, 10),
('chemisiers-salma', 'DOS-048', 'DOS-048-BO-M', 'Bordeaux nuit', 'M', null, 10),
('chemisiers-salma', 'DOS-048', 'DOS-048-BO-L', 'Bordeaux nuit', 'L', null, 10),
('chemisiers-salma', 'DOS-048', 'DOS-048-BO-XL', 'Bordeaux nuit', 'XL', null, 10),
('chemisiers-ines', 'DOS-049', 'DOS-049-RO-S', 'Rose', 'S', null, 11),
('chemisiers-ines', 'DOS-049', 'DOS-049-RO-M', 'Rose', 'M', null, 11),
('chemisiers-ines', 'DOS-049', 'DOS-049-RO-L', 'Rose', 'L', null, 11),
('chemisiers-ines', 'DOS-049', 'DOS-049-RO-XL', 'Rose', 'XL', null, 11),
('chemisiers-maya', 'DOS-050', 'DOS-050-NO-S', 'Noir', 'S', null, 1),
('chemisiers-maya', 'DOS-050', 'DOS-050-NO-M', 'Noir', 'M', null, 1),
('chemisiers-maya', 'DOS-050', 'DOS-050-NO-L', 'Noir', 'L', null, 1),
('chemisiers-maya', 'DOS-050', 'DOS-050-NO-XL', 'Noir', 'XL', null, 1),
('chemisiers-amira', 'DOS-051', 'DOS-051-MA-S', 'Marron', 'S', null, 2),
('chemisiers-amira', 'DOS-051', 'DOS-051-MA-M', 'Marron', 'M', null, 2),
('chemisiers-amira', 'DOS-051', 'DOS-051-MA-L', 'Marron', 'L', null, 2),
('chemisiers-amira', 'DOS-051', 'DOS-051-MA-XL', 'Marron', 'XL', null, 2),
('chemisiers-leila', 'DOS-052', 'DOS-052-BO-S', 'Bordeaux', 'S', null, 14),
('chemisiers-leila', 'DOS-052', 'DOS-052-BO-M', 'Bordeaux', 'M', null, 14),
('chemisiers-leila', 'DOS-052', 'DOS-052-BO-L', 'Bordeaux', 'L', null, 14),
('chemisiers-leila', 'DOS-052', 'DOS-052-BO-XL', 'Bordeaux', 'XL', null, 14),
('chemisiers-sofia', 'DOS-053', 'DOS-053-OR-S', 'Or champagne', 'S', null, 15),
('chemisiers-sofia', 'DOS-053', 'DOS-053-OR-M', 'Or champagne', 'M', null, 15),
('chemisiers-sofia', 'DOS-053', 'DOS-053-OR-L', 'Or champagne', 'L', null, 15),
('chemisiers-sofia', 'DOS-053', 'DOS-053-OR-XL', 'Or champagne', 'XL', null, 15),
('chemisiers-dalia', 'DOS-054', 'DOS-054-SA-S', 'Sable', 'S', null, 16),
('chemisiers-dalia', 'DOS-054', 'DOS-054-SA-M', 'Sable', 'M', null, 16),
('chemisiers-dalia', 'DOS-054', 'DOS-054-SA-L', 'Sable', 'L', null, 16),
('chemisiers-dalia', 'DOS-054', 'DOS-054-SA-XL', 'Sable', 'XL', null, 16),
('chemisiers-mina', 'DOS-055', 'DOS-055-BO-S', 'Bordeaux nuit', 'S', null, 0),
('chemisiers-mina', 'DOS-055', 'DOS-055-BO-M', 'Bordeaux nuit', 'M', null, 0),
('chemisiers-mina', 'DOS-055', 'DOS-055-BO-L', 'Bordeaux nuit', 'L', null, 0),
('chemisiers-mina', 'DOS-055', 'DOS-055-BO-XL', 'Bordeaux nuit', 'XL', null, 0),
('chemisiers-aya', 'DOS-056', 'DOS-056-RO-S', 'Rose', 'S', null, 5),
('chemisiers-aya', 'DOS-056', 'DOS-056-RO-M', 'Rose', 'M', null, 5),
('chemisiers-aya', 'DOS-056', 'DOS-056-RO-L', 'Rose', 'L', null, 5),
('chemisiers-aya', 'DOS-056', 'DOS-056-RO-XL', 'Rose', 'XL', null, 5),
('chemisiers-nadia', 'DOS-057', 'DOS-057-NO-S', 'Noir', 'S', null, 6),
('chemisiers-nadia', 'DOS-057', 'DOS-057-NO-M', 'Noir', 'M', null, 6),
('chemisiers-nadia', 'DOS-057', 'DOS-057-NO-L', 'Noir', 'L', null, 6),
('chemisiers-nadia', 'DOS-057', 'DOS-057-NO-XL', 'Noir', 'XL', null, 6),
('chemisiers-zina', 'DOS-058', 'DOS-058-MA-S', 'Marron', 'S', null, 7),
('chemisiers-zina', 'DOS-058', 'DOS-058-MA-M', 'Marron', 'M', null, 7),
('chemisiers-zina', 'DOS-058', 'DOS-058-MA-L', 'Marron', 'L', null, 7),
('chemisiers-zina', 'DOS-058', 'DOS-058-MA-XL', 'Marron', 'XL', null, 7),
('bijoux-lilas', 'DOS-059', 'DOS-059-BO', 'Bordeaux', null, null, 8),
('bijoux-ambre', 'DOS-060', 'DOS-060-OR', 'Or champagne', null, null, 9),
('bijoux-perle', 'DOS-061', 'DOS-061-SA', 'Sable', null, null, 1),
('bijoux-eclat', 'DOS-062', 'DOS-062-BO', 'Bordeaux nuit', null, null, 2),
('bijoux-aube', 'DOS-063', 'DOS-063-RO', 'Rose', null, null, 12),
('bijoux-jasmin', 'DOS-064', 'DOS-064-NO', 'Noir', null, null, 13),
('bijoux-rubis', 'DOS-065', 'DOS-065-MA', 'Marron', null, null, 14),
('bijoux-opale', 'DOS-066', 'DOS-066-BO', 'Bordeaux', null, null, 15),
('bijoux-tendresse', 'DOS-067', 'DOS-067-OR', 'Or champagne', null, null, 16),
('bijoux-flora', 'DOS-068', 'DOS-068-SA', 'Sable', null, null, 17),
('bijoux-dahlia', 'DOS-069', 'DOS-069-BO', 'Bordeaux nuit', null, null, 5),
('bijoux-etoile', 'DOS-070', 'DOS-070-RO', 'Rose', null, null, 6),
('bijoux-miel', 'DOS-071', 'DOS-071-NO', 'Noir', null, null, 7),
('bijoux-reve', 'DOS-072', 'DOS-072-MA', 'Marron', null, null, 1),
('soins-visage-argan-doux', 'DOS-073', 'DOS-073-BO', 'Bordeaux', null, null, 2),
('soins-visage-rose-de-fes', 'DOS-074', 'DOS-074-OR', 'Or champagne', null, null, 0),
('soins-visage-fleur-d-oranger', 'DOS-075', 'DOS-075-SA', 'Sable', null, null, 11),
('soins-visage-lait-d-amande', 'DOS-076', 'DOS-076-BO', 'Bordeaux nuit', null, null, 12),
('soins-visage-neroli', 'DOS-077', 'DOS-077-RO', 'Rose', null, null, 13),
('soins-visage-miel-pur', 'DOS-078', 'DOS-078-NO', 'Noir', null, null, 14),
('soins-visage-jasmin-blanc', 'DOS-079', 'DOS-079-MA', 'Marron', null, null, 15),
('soins-visage-aloe-vera', 'DOS-080', 'DOS-080-BO', 'Bordeaux', null, null, 16),
('soins-visage-grenade', 'DOS-081', 'DOS-081-OR', 'Or champagne', null, null, 17),
('soins-visage-eau-de-rose', 'DOS-082', 'DOS-082-SA', 'Sable', null, null, 5),
('soins-visage-lavande', 'DOS-083', 'DOS-083-BO', 'Bordeaux nuit', null, null, 1),
('soins-visage-karite', 'DOS-084', 'DOS-084-RO', 'Rose', null, null, 2),
('soins-visage-verveine', 'DOS-085', 'DOS-085-NO', 'Noir', null, null, 8),
('soins-visage-rituel-atlas', 'DOS-086', 'DOS-086-MA', 'Marron', null, null, 9),
('decoration-zellige', 'DOS-087', 'DOS-087-BO', 'Bordeaux', null, null, 10),
('decoration-tanger', 'DOS-088', 'DOS-088-OR', 'Or champagne', null, null, 11),
('decoration-marrakech', 'DOS-089', 'DOS-089-SA', 'Sable', null, null, 12),
('decoration-essaouira', 'DOS-090', 'DOS-090-BO', 'Bordeaux nuit', null, null, 13),
('decoration-babouche', 'DOS-091', 'DOS-091-RO', 'Rose', null, null, 14),
('decoration-safi', 'DOS-092', 'DOS-092-NO', 'Noir', null, null, 15),
('decoration-fes', 'DOS-093', 'DOS-093-MA', 'Marron', null, null, 0),
('decoration-andalousie', 'DOS-094', 'DOS-094-BO', 'Bordeaux', null, null, 1),
('decoration-mosaique', 'DOS-095', 'DOS-095-OR', 'Or champagne', null, null, 2),
('decoration-riad', 'DOS-096', 'DOS-096-SA', 'Sable', null, null, 6),
('decoration-safran', 'DOS-097', 'DOS-097-BO', 'Bordeaux nuit', null, null, 7),
('decoration-tadelakt', 'DOS-098', 'DOS-098-RO', 'Rose', null, null, 8),
('decoration-moucharabieh', 'DOS-099', 'DOS-099-NO', 'Noir', null, null, 9),
('decoration-dar', 'DOS-100', 'DOS-100-MA', 'Marron', null, null, 10)
) as v(slug, product_sku, sku, color, size, shoe, stock) join public.products p on p.slug = v.slug and p.sku = v.product_sku on conflict (sku) do nothing;

insert into public.inventory_movements (variant_id, delta, reason, note)
select v.id, v.stock, 'initial', 'Stock initial (démo)' from public.product_variants v where v.sku in ('DOS-001-BO', 'DOS-001-IV', 'DOS-002-OR', 'DOS-002-BO', 'DOS-003-BO', 'DOS-004-BO-S', 'DOS-004-BO-M', 'DOS-004-BO-L', 'DOS-004-BO-XL', 'DOS-004-CH-S', 'DOS-004-CH-M', 'DOS-004-CH-L', 'DOS-004-CH-XL', 'DOS-005-NO-S', 'DOS-005-NO-M', 'DOS-005-NO-L', 'DOS-005-NO-XL', 'DOS-006-SA-S', 'DOS-006-SA-M', 'DOS-006-SA-L', 'DOS-006-SA-XL', 'DOS-007-BO-37', 'DOS-007-BO-38', 'DOS-007-BO-39', 'DOS-007-BO-40', 'DOS-007-BO-41', 'DOS-008-DO-37', 'DOS-008-DO-38', 'DOS-008-DO-39', 'DOS-008-DO-40', 'DOS-008-DO-41', 'DOS-009-CR-37', 'DOS-009-CR-38', 'DOS-009-CR-39', 'DOS-009-CR-40', 'DOS-009-CR-41', 'DOS-010-RO', 'DOS-011-NA', 'DOS-012-CO', 'DOS-013-IV', 'DOS-014-OR', 'DOS-015-NO', 'DOS-016-BO', 'DOS-017-BO', 'DOS-018-OR', 'DOS-019-SA', 'DOS-020-BO', 'DOS-021-RO', 'DOS-022-NO', 'DOS-023-MA', 'DOS-024-BO', 'DOS-025-OR', 'DOS-026-SA', 'DOS-027-BO', 'DOS-028-RO', 'DOS-029-NO', 'DOS-030-MA', 'DOS-031-BO-37', 'DOS-031-BO-38', 'DOS-031-BO-39', 'DOS-031-BO-40', 'DOS-031-BO-41', 'DOS-032-OR-37', 'DOS-032-OR-38', 'DOS-032-OR-39', 'DOS-032-OR-40', 'DOS-032-OR-41', 'DOS-033-SA-37', 'DOS-033-SA-38', 'DOS-033-SA-39', 'DOS-033-SA-40', 'DOS-033-SA-41', 'DOS-034-BO-37', 'DOS-034-BO-38', 'DOS-034-BO-39', 'DOS-034-BO-40', 'DOS-034-BO-41', 'DOS-035-RO-37', 'DOS-035-RO-38', 'DOS-035-RO-39', 'DOS-035-RO-40', 'DOS-035-RO-41', 'DOS-036-NO-37', 'DOS-036-NO-38', 'DOS-036-NO-39', 'DOS-036-NO-40', 'DOS-036-NO-41', 'DOS-037-MA-37', 'DOS-037-MA-38', 'DOS-037-MA-39', 'DOS-037-MA-40', 'DOS-037-MA-41', 'DOS-038-BO-37', 'DOS-038-BO-38', 'DOS-038-BO-39', 'DOS-038-BO-40', 'DOS-038-BO-41', 'DOS-039-OR-37', 'DOS-039-OR-38', 'DOS-039-OR-39', 'DOS-039-OR-40', 'DOS-039-OR-41', 'DOS-040-SA-37', 'DOS-040-SA-38', 'DOS-040-SA-39', 'DOS-040-SA-40', 'DOS-040-SA-41', 'DOS-041-BO-37', 'DOS-041-BO-38', 'DOS-041-BO-39', 'DOS-041-BO-40', 'DOS-041-BO-41', 'DOS-042-RO-37', 'DOS-042-RO-38', 'DOS-042-RO-39', 'DOS-042-RO-40', 'DOS-042-RO-41', 'DOS-043-NO-37', 'DOS-043-NO-38', 'DOS-043-NO-39', 'DOS-043-NO-40', 'DOS-043-NO-41', 'DOS-044-MA-37', 'DOS-044-MA-38', 'DOS-044-MA-39', 'DOS-044-MA-40', 'DOS-044-MA-41', 'DOS-045-BO-S', 'DOS-045-BO-M', 'DOS-045-BO-L', 'DOS-045-BO-XL', 'DOS-046-OR-S', 'DOS-046-OR-M', 'DOS-046-OR-L', 'DOS-046-OR-XL', 'DOS-047-SA-S', 'DOS-047-SA-M', 'DOS-047-SA-L', 'DOS-047-SA-XL', 'DOS-048-BO-S', 'DOS-048-BO-M', 'DOS-048-BO-L', 'DOS-048-BO-XL', 'DOS-049-RO-S', 'DOS-049-RO-M', 'DOS-049-RO-L', 'DOS-049-RO-XL', 'DOS-050-NO-S', 'DOS-050-NO-M', 'DOS-050-NO-L', 'DOS-050-NO-XL', 'DOS-051-MA-S', 'DOS-051-MA-M', 'DOS-051-MA-L', 'DOS-051-MA-XL', 'DOS-052-BO-S', 'DOS-052-BO-M', 'DOS-052-BO-L', 'DOS-052-BO-XL', 'DOS-053-OR-S', 'DOS-053-OR-M', 'DOS-053-OR-L', 'DOS-053-OR-XL', 'DOS-054-SA-S', 'DOS-054-SA-M', 'DOS-054-SA-L', 'DOS-054-SA-XL', 'DOS-055-BO-S', 'DOS-055-BO-M', 'DOS-055-BO-L', 'DOS-055-BO-XL', 'DOS-056-RO-S', 'DOS-056-RO-M', 'DOS-056-RO-L', 'DOS-056-RO-XL', 'DOS-057-NO-S', 'DOS-057-NO-M', 'DOS-057-NO-L', 'DOS-057-NO-XL', 'DOS-058-MA-S', 'DOS-058-MA-M', 'DOS-058-MA-L', 'DOS-058-MA-XL', 'DOS-059-BO', 'DOS-060-OR', 'DOS-061-SA', 'DOS-062-BO', 'DOS-063-RO', 'DOS-064-NO', 'DOS-065-MA', 'DOS-066-BO', 'DOS-067-OR', 'DOS-068-SA', 'DOS-069-BO', 'DOS-070-RO', 'DOS-071-NO', 'DOS-072-MA', 'DOS-073-BO', 'DOS-074-OR', 'DOS-075-SA', 'DOS-076-BO', 'DOS-077-RO', 'DOS-078-NO', 'DOS-079-MA', 'DOS-080-BO', 'DOS-081-OR', 'DOS-082-SA', 'DOS-083-BO', 'DOS-084-RO', 'DOS-085-NO', 'DOS-086-MA', 'DOS-087-BO', 'DOS-088-OR', 'DOS-089-SA', 'DOS-090-BO', 'DOS-091-RO', 'DOS-092-NO', 'DOS-093-MA', 'DOS-094-BO', 'DOS-095-OR', 'DOS-096-SA', 'DOS-097-BO', 'DOS-098-RO', 'DOS-099-NO', 'DOS-100-MA') and exists (select 1 from public.products p where p.id = v.product_id and p.sku = left(v.sku, 7) and p.slug in ('sac-riviera', 'sac-bandouliere-aurore', 'cabas-signature', 'robe-satin-soraya', 'abaya-elegance', 'chemise-lin-nadia', 'escarpins-velours', 'sandales-dorees-mira', 'baskets-creme', 'savon-rose-argan', 'savon-noir-beldi', 'coffret-savons-dossora', 'foulard-soie-ivoire', 'collier-perle-or', 'lunettes-diva', 'ceinture-cuir-gold', 'sacs-a-dos-atlas', 'sacs-a-dos-medina', 'sacs-a-dos-oasis', 'sacs-a-dos-rivage', 'sacs-a-dos-kasbah', 'sacs-a-dos-nomade', 'sacs-a-dos-aquarelle', 'sacs-a-dos-soleil', 'sacs-a-dos-jardin', 'sacs-a-dos-majorelle', 'sacs-a-dos-dune', 'sacs-a-dos-emeraude', 'sacs-a-dos-serenite', 'sacs-a-dos-palmier', 'baskets-cedre', 'baskets-casablanca', 'baskets-nuage', 'baskets-luna', 'baskets-eclipse', 'baskets-avenue', 'baskets-lumiere', 'baskets-etoile', 'baskets-saphir', 'baskets-nacre', 'baskets-mistral', 'baskets-velours', 'baskets-cobalt', 'baskets-sahara', 'chemisiers-nour', 'chemisiers-lina', 'chemisiers-yasmine', 'chemisiers-salma', 'chemisiers-ines', 'chemisiers-maya', 'chemisiers-amira', 'chemisiers-leila', 'chemisiers-sofia', 'chemisiers-dalia', 'chemisiers-mina', 'chemisiers-aya', 'chemisiers-nadia', 'chemisiers-zina', 'bijoux-lilas', 'bijoux-ambre', 'bijoux-perle', 'bijoux-eclat', 'bijoux-aube', 'bijoux-jasmin', 'bijoux-rubis', 'bijoux-opale', 'bijoux-tendresse', 'bijoux-flora', 'bijoux-dahlia', 'bijoux-etoile', 'bijoux-miel', 'bijoux-reve', 'soins-visage-argan-doux', 'soins-visage-rose-de-fes', 'soins-visage-fleur-d-oranger', 'soins-visage-lait-d-amande', 'soins-visage-neroli', 'soins-visage-miel-pur', 'soins-visage-jasmin-blanc', 'soins-visage-aloe-vera', 'soins-visage-grenade', 'soins-visage-eau-de-rose', 'soins-visage-lavande', 'soins-visage-karite', 'soins-visage-verveine', 'soins-visage-rituel-atlas', 'decoration-zellige', 'decoration-tanger', 'decoration-marrakech', 'decoration-essaouira', 'decoration-babouche', 'decoration-safi', 'decoration-fes', 'decoration-andalousie', 'decoration-mosaique', 'decoration-riad', 'decoration-safran', 'decoration-tadelakt', 'decoration-moucharabieh', 'decoration-dar')) and not exists (select 1 from public.inventory_movements m where m.variant_id = v.id and m.reason = 'initial' and m.note = 'Stock initial (démo)');

insert into public.shipping_countries (code, name_fr, name_en, name_ar, currency, exchange_rate, fee, free_shipping_threshold, eta_min_days, eta_max_days, sort_order) values
('MA', 'Maroc', 'Morocco', 'المغرب', 'MAD', 1, 80, 1000, 2, 5, 1),
('FR', 'France', 'France', 'فرنسا', 'EUR', 10.8, 15, 1500, 5, 10, 2),
('US', 'États-Unis', 'United States', 'الولايات المتحدة', 'USD', 10, 25, null, 7, 14, 3),
('CA', 'Canada', 'Canada', 'كندا', 'CAD', 7.3, 30, null, 7, 14, 4),
('SN', 'Sénégal', 'Senegal', 'السنغال', 'XOF', 0.0165, 10000, null, 5, 10, 5),
('CI', 'Côte d''Ivoire', 'Ivory Coast', 'ساحل العاج', 'XOF', 0.0165, 10000, null, 5, 10, 6)
on conflict (code) do nothing;

insert into public.shipping_cities (country_code, name) values
('MA', 'Casablanca'),
('MA', 'Rabat'),
('MA', 'Marrakech'),
('MA', 'Fès'),
('MA', 'Tanger'),
('MA', 'Agadir'),
('MA', 'Meknès'),
('MA', 'Oujda'),
('MA', 'Tétouan'),
('MA', 'Kénitra'),
('MA', 'Salé'),
('MA', 'Laâyoune'),
('FR', 'Paris'),
('FR', 'Lyon'),
('FR', 'Marseille'),
('FR', 'Toulouse'),
('FR', 'Lille'),
('FR', 'Bordeaux'),
('FR', 'Nice'),
('FR', 'Nantes'),
('FR', 'Strasbourg'),
('US', 'New York'),
('US', 'Los Angeles'),
('US', 'Chicago'),
('US', 'Houston'),
('US', 'Miami'),
('US', 'Washington'),
('CA', 'Montréal'),
('CA', 'Toronto'),
('CA', 'Québec'),
('CA', 'Ottawa'),
('CA', 'Vancouver'),
('SN', 'Dakar'),
('SN', 'Thiès'),
('SN', 'Saint-Louis'),
('CI', 'Abidjan'),
('CI', 'Bouaké'),
('CI', 'Yamoussoukro')
on conflict do nothing;

insert into public.payment_methods (code, name_fr, name_en, name_ar, instructions_fr, instructions_en, instructions_ar, account_details, morocco_only, sort_order) values
('cih_bank', 'CIH Bank', 'CIH Bank', 'بنك CIH', 'Effectuez le paiement avec les coordonnées ci-dessous, puis envoyez la preuve depuis votre commande ou par WhatsApp.', 'Make the payment using the details below, then send the proof from your order or via WhatsApp.', 'أرسل المبلغ بالمعلومات أدناه ثم ابعث الإثبات من طلبك أو عبر واتساب.', 'À renseigner dans Admin → Paiements (bénéficiaire, RIB / numéro).', false, 1),
('wafacash', 'Wafacash', 'Wafacash', 'وفاكاش', 'Effectuez le paiement avec les coordonnées ci-dessous, puis envoyez la preuve depuis votre commande ou par WhatsApp.', 'Make the payment using the details below, then send the proof from your order or via WhatsApp.', 'أرسل المبلغ بالمعلومات أدناه ثم ابعث الإثبات من طلبك أو عبر واتساب.', 'À renseigner dans Admin → Paiements (bénéficiaire, RIB / numéro).', false, 2),
('western_union', 'Western Union', 'Western Union', 'ويسترن يونيون', 'Effectuez le paiement avec les coordonnées ci-dessous, puis envoyez la preuve depuis votre commande ou par WhatsApp.', 'Make the payment using the details below, then send the proof from your order or via WhatsApp.', 'أرسل المبلغ بالمعلومات أدناه ثم ابعث الإثبات من طلبك أو عبر واتساب.', 'À renseigner dans Admin → Paiements (bénéficiaire, RIB / numéro).', false, 3),
('moneygram', 'MoneyGram', 'MoneyGram', 'موني غرام', 'Effectuez le paiement avec les coordonnées ci-dessous, puis envoyez la preuve depuis votre commande ou par WhatsApp.', 'Make the payment using the details below, then send the proof from your order or via WhatsApp.', 'أرسل المبلغ بالمعلومات أدناه ثم ابعث الإثبات من طلبك أو عبر واتساب.', 'À renseigner dans Admin → Paiements (bénéficiaire, RIB / numéro).', false, 4),
('wave', 'Wave', 'Wave', 'Wave', 'Effectuez le paiement avec les coordonnées ci-dessous, puis envoyez la preuve depuis votre commande ou par WhatsApp.', 'Make the payment using the details below, then send the proof from your order or via WhatsApp.', 'أرسل المبلغ بالمعلومات أدناه ثم ابعث الإثبات من طلبك أو عبر واتساب.', 'À renseigner dans Admin → Paiements (bénéficiaire, RIB / numéro).', false, 5),
('bank_transfer', 'Virement bancaire', 'Bank transfer', 'تحويل بنكي', 'Effectuez le paiement avec les coordonnées ci-dessous, puis envoyez la preuve depuis votre commande ou par WhatsApp.', 'Make the payment using the details below, then send the proof from your order or via WhatsApp.', 'أرسل المبلغ بالمعلومات أدناه ثم ابعث الإثبات من طلبك أو عبر واتساب.', 'À renseigner dans Admin → Paiements (bénéficiaire, RIB / numéro).', false, 6),
('cod', 'Paiement à la livraison (Maroc)', 'Cash on delivery (Morocco)', 'الدفع عند الاستلام (المغرب)', 'Vous réglez en espèces au livreur à la réception (Maroc uniquement).', 'You pay the courier in cash on delivery (Morocco only).', 'تدفع نقدًا للموزع عند الاستلام (المغرب فقط).', null, true, 7)
on conflict (code) do nothing;

insert into public.discount_codes (code, percent, min_order, is_active) values ('DOSSORA10', 10, 200, true) on conflict (code) do nothing;

insert into public.homepage_banners (title_fr, title_en, title_ar, subtitle_fr, subtitle_en, subtitle_ar, button_label_fr, button_label_en, button_label_ar, link_url, image_desktop_url, image_mobile_url, sort_order)
select v.title_fr, v.title_en, v.title_ar, v.subtitle_fr, v.subtitle_en, v.subtitle_ar, v.button_label_fr, v.button_label_en, v.button_label_ar, v.link_url, v.image_desktop_url, v.image_mobile_url, v.sort_order from (values
('Nouvelle collection', 'New collection', 'المجموعة الجديدة', 'Des pièces élégantes pour chaque instant.', 'Elegant pieces for every moment.', 'قطع أنيقة لكل لحظة.', 'Découvrir', 'Discover', 'اكتشفي', '/shop?flag=new', '/demo/banner-1.svg', '/demo/banner-1-m.svg', 1),
('Collection sacs', 'Bag collection', 'مجموعة الحقائب', 'Le sac qui complète toutes vos tenues.', 'The bag that completes every outfit.', 'الحقيبة التي تكمل كل إطلالاتك.', 'Voir les sacs', 'Shop bags', 'تسوقي الحقائب', '/shop?category=sacs', '/demo/banner-2.svg', '/demo/banner-2-m.svg', 2),
('Promotions', 'Special offers', 'عروض خاصة', 'Profitez de prix doux sur une sélection.', 'Enjoy gentle prices on a selection.', 'استفيدي من أسعار مميزة على مختارات.', 'Voir les offres', 'See offers', 'شاهدي العروض', '/shop?flag=sale', '/demo/banner-3.svg', '/demo/banner-3-m.svg', 3)
) as v(title_fr, title_en, title_ar, subtitle_fr, subtitle_en, subtitle_ar, button_label_fr, button_label_en, button_label_ar, link_url, image_desktop_url, image_mobile_url, sort_order)
where not exists (select 1 from public.homepage_banners b where b.link_url = v.link_url and b.image_desktop_url = v.image_desktop_url);
